# Generated by Django 3.2.9 on 2021-11-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number_of_image']},
        ),
        migrations.AlterField(
            model_name='image',
            name='number_of_image',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер картинки'),
        ),
    ]
